# Generated by Django 6.0 on 2025-12-27 07:16

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHandling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='MachineMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('machine_name', models.CharField(blank=True, max_length=150, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnc_order_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='order_image')),
                ('stone', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('packing_instruction', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateField()),
                ('exp_delivery_date', models.DateField()),
                ('coverage_area', models.CharField(max_length=50)),
                ('party_name', models.CharField(max_length=200)),
                ('sales_person', models.CharField(max_length=100)),
                ('dispatch_status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MachineDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_details', to='cnc_work_app.machinemaster')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_details', to='cnc_work_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('qty', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc_work_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='DesignFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='design_file')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc_work_app.order')),
            ],
        ),
    ]
