# Generated by Django 5.0.1 on 2025-12-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_work_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='machinedetail',
            name='machine_name',
        ),
        migrations.RemoveField(
            model_name='machinedetail',
            name='order',
        ),
        migrations.AlterField(
            model_name='imagehandling',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cnc_order_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='DesignFile',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='MachineMaster',
        ),
        migrations.DeleteModel(
            name='MachineDetail',
        ),
    ]
