# Generated by Django 6.0 on 2025-12-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_work_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/'),
        ),
    ]
