# Generated by Django 6.0 on 2025-12-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_work_app', '0002_alter_order_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='exp_delivery_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='stone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
