# Generated by Django 6.0 on 2025-12-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_work_app', '0003_remove_order_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='exp_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
